# Welcome to Jekyll!

# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Omnia Mohamed
tagline: Quantum Computing Enthusiast & Researcher
email: omnia.raouf.01@gmail.com
twitter_username: Omnia_Raouf_
github_username:  OmniaRaouf101
twitter:
  - username: Omnia_Raouf_
description: Omnia Mohamed is a physics graduate with a strong interest in quantum computing, machine learning, and their applications in various fields. She is passionate about making quantum computing more accessible through research, education, and collaboration.
author: Omnia Mohamed
url: https://OmniaRaouf101.github.io

# Reading Files
include:
  - _pages
  - _posters

# Collections
collections:
  news:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "news"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
